trendy_vidz/urls.py
from django.contrib import admin, auth
from django.urls import path
from vid_lib import views
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    # Auth
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('signup/', views.signup_view.as_view(),name='signup'),
    # group
    path('group/crt/', views.group_crt.as_view(),name='grp_crt'),
    path('group/<int:pk>/', views.group_dtl.as_view(), name='grp_dtl'),
    path('group/<int:pk>/updt/', views.group_updt.as_view(), name='grp_updt'),
    path('group/<int:pk>/dlt/', views.group_dlt.as_view(), name='grp_dlt'),
    # video
    path('group/<int:pk>/addvideo/', views.add_video, name='add_video'),
    path('video/search/', views.video_search, name='video_search'),
    path('vid/<int:pk>/dlt/', views.video_dlt.as_view(), name='vid_dlt'),
    # dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
]

vid_lib/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class group(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('grp_dtl', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class video(models.Model):
    title = models.CharField(max_length=50)
    url =models.URLField()
    u_tube_id = models.CharField(max_length=50)
    group = models.ForeignKey(group, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

vid_lib/forms.py
from . import models
from django import forms


class video_form(forms.ModelForm):
    class Meta:
        model = models.video
        fields = ['url']
        labels = {'url':'Youtube URL'}


class search_form(forms.Form):
    search_term = forms.CharField(label='Search for a video')

vid_lib/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, Http404
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . import models, forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import urllib, requests

YOUTUBE_API_KEY = 'AIzaSyAgIOeV6Z6nhglm4HNFYP_3dWMHnGhD2As'

def home(request):
    recent_vid = models.video.objects.order_by('-id')[:3]
    return render(request, 'vid_lib/home.html',{'recent_vid':recent_vid})


class signup_view(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username,password=password)
        login(self.request, user)
        return redirect('home')


class group_crt(LoginRequiredMixin, generic.CreateView):
    model = models.group
    login_url = '/login/'
    template_name = 'vid_lib/group_form_crt_updt.html'
    fields = ['title']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class group_dtl(LoginRequiredMixin, generic.DetailView):
    model = models.group
    login_url = '/login/'

    def get_object(self):
        group = super().get_object()
        if not group.user == self.request.user:
            raise Http404
        return group

class group_updt(LoginRequiredMixin, generic.UpdateView):
    model = models.group
    fields = ['title']
    login_url = '/login/'
    template_name = 'vid_lib/group_form_crt_updt.html'

    def get_object(self):
        group = super().get_object()
        if not group.user == self.request.user:
            raise Http404
        return group

class group_dlt(LoginRequiredMixin, generic.DeleteView):
    model = models.group
    login_url = '/login/'
    template_name = 'vid_lib/confirm_delete.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        group = super().get_object()
        if not group.user == self.request.user:
            raise Http404
        return group

@login_required(login_url='/login/')
def add_video(request, pk):
    form = forms.video_form()
    search_form = forms.search_form()
    group = get_object_or_404(models.group ,pk=pk, user=request.user)
    if request.method == 'POST':
        form = forms.video_form(request.POST)
        if form.is_valid():
            form.instance.group = group
            parsed_url = urllib.parse.urlparse(request.POST['url'])
            u_tube_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            form.instance.u_tube_id = u_tube_id[0]
            responce = requests.get(f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={ u_tube_id[0] }&key={YOUTUBE_API_KEY}')
            json = responce.json()
            form.instance.title = json['items'][0]['snippet']['title']
            form.save()
            return redirect('grp_dtl', pk=pk)

    return render(request, 'vid_lib/add_vid.html', {'form':form, 'search_form':search_form})


def video_search(request):
    search_form = forms.search_form(request.GET)
    if search_form.is_valid():
        search = request.GET['search_term']
        responce = requests.get(f'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={search}&key={ YOUTUBE_API_KEY }')
        json = responce.json()
        return JsonResponse(json)
    return JsonResponse({'rsp_data':'not working'})


class video_dlt(LoginRequiredMixin, generic.DeleteView):
    model = models.video
    login_url = '/login/'
    template_name = 'vid_lib/confirm_delete.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super().get_object()
        if not video.group.user == self.request.user:
            raise Http404
        return video

@login_required(login_url='/login/')
def dashboard(request):
    groups = models.group.objects.filter(user=request.user)
    return render(request, 'vid_lib/dashboard.html', {'groups':groups})

vid_lib/templates/vid_lib/add_vid.html
{% extends "vid_lib/base.html" %}
{% block content %}
{% load bootstrap4 %}
  <form method="POST" id="submit_form">
    {% bootstrap_form form %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
  <br>
  <h2>OR</h2>
<form>
{% bootstrap_form search_form %}
</form>
<div id="search_result"></div>
<script>
  var delay_timer;
  $("#id_search_term").keyup(function(){
    clearTimeout(delay_timer);
   $("#search_result").text("loading..");
   delay_timer = setTimeout(function(){
     var text = $("#id_search_term").val();
     $.ajax({
       url: '/video/search/',
       data: {
         'search_term': text
       },
       dataType: 'json',
       success: function(data){

         var result = '';
         $("#search_result").text("");
         result += '<div class="row">';
         data['items'].forEach(function(item){
           result += '<div class="col-md-4"><div class="card mb-4 shadow-sm">';
           result += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + item['id']['videoId'] + '" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
           result += '<a href="#" class="btn btn-primary" onclick="add_video(\''+ item['id']['videoId'] +'\')">Add</a>'
           result += '</div></div>';
         });
         result += '</div>';
         $("#search_result").html(result);
       }
     });
   }, 1500);
 });

 function add_video(video_id){
   console.log(video_id)
   $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
   $('#submit_form').submit();
 }
</script>
{% endblock %}

vid_lib/templates/vid_lib/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>trendy_vidz</title>
  <link href="{% static "custom.css" %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Trendy Vidzz</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url "dashboard" %}">Dashboard</a>
      <a class="p-2 text-dark" href="{% url "logout" %}">Log Out</a>
      {% else %}
      <a class="p-2 text-dark" href="{% url "login" %}">Log In</a>
      {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
    <a class="btn btn-outline-primary" href="{% url "signup" %}">Sign up</a>
    {% endif %}
  </div>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

vid_lib/templates/vid_lib/confirm_delete.html
{% extends "vid_lib/base.html" %}
{% block  content%}
<form method="POST">
  {% csrf_token %}
  <p>do u wnat to delete {{object}}?</p>
  <button type="submit" class="btn btn-danger">Delete</button>
</form>
{% endblock %}

vid_lib/templates/vid_lib/dashboard.html
{% extends "vid_lib/base.html" %}
{% block content %}
<div class="text-center">
  <h1>{{user.username}}'s Group</h1>
  <a href="{% url "grp_crt" %}" class="btn btn-primary">Create New Group</a>
</div>
{% for group in groups %}
  <h2><a href="{% url "grp_dtl" pk=group.pk %}">{{group}}</a></h2>
  <div class="row">
    {% for video in group.video_set.all|slice:":3" %}
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">'
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.u_tube_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
    {% endfor %}
  </div>
{% endfor %}
{% endblock %}

vid_lib/templates/vid_lib/group_detail.html
{% extends "vid_lib/base.html" %}
{% block content %}
<h1>{{object}}</h1>
<p>by {{object.user}}</p>
<a class="btn btn-primary" href="{% url "add_video" pk=object.pk %}">Add Video</a>
<a class="btn btn-warning" href="{% url "grp_updt" pk=object.pk %}">Update</a>
<a class="btn btn-danger" href="{% url "grp_dlt" pk=object.pk %}">Delete</a>
<div class="row">
  {% for video in group.video_set.all %}
  <div class="col-md-4">
    <div class="card mb-4 shadow-sm">'
      <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.u_tube_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <a href="{% url "vid_dlt" pk=video.pk %}" class="btn btn-danger">Delete Video</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

vid_lib/templates/vid_lib/group_form_crt_updt.html
{% extends "vid_lib/base.html" %}
{% block content %}
{% load bootstrap4 %}
  <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>

{% endblock %}

vid_lib/templates/vid_lib/home.html
{% extends "vid_lib/base.html" %}
{% block content %}
<div class="jumbotron text-center">
  <h1 class="jumbotron-heading">welcome to trendy videos</h1>
  <p class="text-muted">find and make your own trendy videos</p>
  <p>
    <a href="{% url "grp_crt" %}" class="btn btn-primary">Create new group</a>
  </p>
</div>
<h2>Trendy one</h2>
<div class="row">
  {% for video in recent_vid %}
  <div class="col-lg-4">
  <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.u_tube_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  {% endfor %}
</div>
{% endblock %}